version: "3"

vars:
    CMAKE_APP_BD    : .build/app
    CMAKE_RAYLIB_BD : .build/raylib
    CMAKE_APP_IP    : .install/app
    CMAKE_LUAJIT_IP : .install/luajit
    CMAKE_RAYLIB_IP : .install/raylib
    LUAJIT_DD       : dependencies/luajit
    RAYLIB_DD       : dependencies/raylib

tasks:  
    clean:
        desc: "Remove all .build and .install folders"
        cmds:
            - cmd: cmd /C "if exist .build rmdir /S /Q .build"
              platforms: [windows]
            - cmd: cmd /C "if exist .install rmdir /S /Q .install"
              platforms: [windows]
            - cmd: rm -rf .build .install
              platforms: [linux, darwin]

    fetch:
        desc: "Clone required dependencies"
        vars:
            LUAJIT_GIT: https://github.com/LuaJIT/LuaJIT.git
            RAYLIB_GIT: https://github.com/raysan5/raylib.git
        cmds:
            - git clone --branch v2.1 {{.LUAJIT_GIT}} {{.LUAJIT_DD}}
            - git clone --branch 5.5 --depth 1 {{.RAYLIB_GIT}} {{.RAYLIB_DD}}

    br:
        desc: "Build, install, then run app"
        deps: [build:app]
        cmd: task run
    
    build:app:
        aliases:
          - build
        desc: "Build and install this project"
        cmd: cmake --build {{.CMAKE_APP_BD}} --target install

    build:luajit:
        desc: "Build and install LuaJIT dependencies"
        vars:
            PREF: '{{.ROOT_DIR}}/{{.CMAKE_LUAJIT_IP}}'
            IINC: '{{.ROOT_DIR}}/{{.CMAKE_LUAJIT_IP}}/include'
        dir: dependencies/luajit
        env:
            MACOSX_DEPLOYMENT_TARGET: 10.14
        cmds:
            - cmd: make CC=clang BUILDMODE=dynamic TARGET_LIBPATH=@rpath
              platforms: [darwin]
            - cmd: make PREFIX={{.PREF}} INSTALL_INC={{.IINC}} install
              platforms: [darwin]

    build:raylib:
        desc: "Build and install Raylib dependencies"
        cmd: cmake --build {{.CMAKE_RAYLIB_BD}} --target install

    configure:app:
        desc: "Configure CMake this project"
        cmds:
            - cmake -B {{.CMAKE_APP_BD}} -S .
              -DCMAKE_INSTALL_PREFIX={{.CMAKE_APP_IP}}
    
    configure:raylib:
        desc: "Configure CMake for Raylib dependencies"
        cmds:
            - cmake -B {{.CMAKE_RAYLIB_BD}} -S {{.RAYLIB_DD}}
              -DCMAKE_INSTALL_PREFIX={{.CMAKE_RAYLIB_IP}}
              -DBUILD_SHARED_LIBS=ON
              -DBUILD_EXAMPLES=OFF
              -DENABLE_ASAN=OFF
              -DENABLE_UBSAN=OFF
              -DENABLE_MSAN=OFF
    
    compile:
        desc: "Configure, build, and install project and dependencies"
        deps: [build:luajit, configure:raylib]
        cmds:
            - task build:raylib
            - task configure:app
            - task build:app

    run:app:
        aliases:
          - run
        desc: "Run app from default install target"
        cmds:
            - cmd: ./.install/app/bin/app.exe
              platforms: [windows]
            - cmd: ./.install/app/bin/app
              platforms: [linux]
            - cmd: ./.install/app/Application.app/Contents/MacOS/Application
              platforms: [darwin]
